name: Heroku Docker Deploy
author: Tarun Kashypap
description: Heroku Docker Deploy enables you to deploy containerized apps on Heroku by packaging your app in a Docker image and pushing it to the platform for seamless deployment and scaling.

inputs:
    HEROKU_APP_NAME:
        description: "The name of your Heroku app to deploy the Docker container."
        required: true
        default: "myapp-demo"

    HEROKU_API_KEY:
        description: "The API key used to authenticate with Heroku for deployment."
        required: true

runs:
    using: 'composite'
    env:
        HEROKU_API_KEY: ${{inputs.HEROKU_API_KEY}}
    steps:
        - name: Build docker image
          run: docker image build -t ${{inputs.HEROKU_APP_NAME}} .
        - name: Log in tot he Heroku Container Registry
          run: heroku container:login             
        - name: Check HEROKU_APP_NAME Exists
          id: checkHerokuApp
          run: |
            result=$(heroku apps | grep -wx ${{inputs.HEROKU_APP_NAME}} > /dev/null && echo "true" || echo "false"); echo "result=$result" >> $GITHUB_OUTPUT
            echo "appNameExists=$result" >> $GITHUB_OUTPUT
        
        - name: Create App container in Heroku
          if: steps.checkHerokuApp.outputs.appNameExists == 'false'
          run: heroku create ${{inputs.HEROKU_APP_NAME}} --stack container
        - name: Tag docker image to heroku repository
          run: docker image tag ${{inputs.HEROKU_APP_NAME}} registry.heroku.com/${{inputs.HEROKU_APP_NAME}}/web
        - name: Push image to heroku repository
          run: docker push registry.heroku.com/${{inputs.HEROKU_APP_NAME}}/web
        - name: Release to the heroku
          run: heroku container:release web -a ${{inputs.HEROKU_APP_NAME}}
        