name: Deploy NextUI on Heroku

on:
    push:
        branches: 
            ["main"]
    workflow_dispatch: 

jobs:
    test:
        name: Test NextUI
        runs-on: ubuntu-latest
        steps:
            - name: Get Code
              uses: actions/checkout@v4

            - name: Install Node.Js
              uses: actions/setup-node@v4
              with:
                node-version: 20.6.0

            - name: Install Dependancies
              run: npm install

            - name: Test lint
              run: npm run lint
            
            - name: Check docker image is creating or not
              run: docker image build -t nextui-demo-app .

    deploy:
        name: Deploy to Heroku
        runs-on: ubuntu-latest
        steps:
            - name: Get Code
              uses: actions/checkout@v4

            - name: Login Docker
              run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

            - name: Build docker image
              run: docker image build -t tarunkashyap6665/nextui-demo-app .

            - name: Log in tot he Heroku Container Registry
              run: heroku container:login
              env:
                HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY}}
            
            - name: Create App container in Heroku
              run: heroku create nextui-demo-app --stack container
              env:
                HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY}}

            - name: Tag docker image to heroku repository
              run: docker image tag tarunkashyap6665/nextui-demo-app registry.heroku.com/tarunkashyap6665/nextui-demo-app/web

            - name: Push image to heroku repository
              run: docker push registry.heroku.com/tarunkashyap6665/nextui-demo-app/web
              env:
                HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY}}

            - name: Release to the heroku
              run: heroku container:release web -a nextui-demo-app
              env:
                HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY}}

            
            