name: Example Workflow

on: [push]

jobs:
  set-output-example:
    env:
        HEROKU_APP_NAME: nextui-demo
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run grep command
        id: grep_step
        run: |
          result=$(cat sample.txt | grep -wx ${{env.HEROKU_APP_NAME}})
          echo "result=$result" >> $GITHUB_OUTPUT
          
      - name: Use output
        if: steps.grep_step.outputs.result == env.HEROKU_APP_NAME
        run: |
            echo "The grep result is: ${{ env.result }}"

      - name: Else
        if: steps.grep_step.outputs.result != env.HEROKU_APP_NAME
        run: |
            echo "else"