name: Example Workflow

on: [push]

jobs:
  set-output-example:
    env:
        HEROKU_APP_NAME: nextui-demo
        HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY}}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run grep command
        id: grep_step
        run: |
          result=$(heroku apps | grep -wx ${{env.HEROKU_APP_NAME}} && echo "true" || echo "false")
          echo "result=$result" >> $GITHUB_OUTPUT
          
      - name: Use output
        run: |
            echo "The grep result is: ${{ steps.grep_step.outputs.result }}"

      - name: Else
        run: |
            echo "else  ${{ steps.grep_step.outputs.result }}"